examples/games/life/life.go

A small example piece of an implementation of Conway's Game of Life.

Conway's Game of Life

---

raymath/raymath.go

It seems the x, y, z were in the wrong place.

Fix translate matrix creation.

---

examples/physics/chipmunk/main.go

I saw #19 and thought I'd replace the chipmunk example with my own port.
I did this quickly so let me know if anything needs fixing.

use jakecoffman port of chipmunk instead of vova616

---

examples/core/3d_picking/main.go

Remove left over warning that's no longer accurate

---

examples/games/snake/main.go

Noticed a minor mistake on the way through, mainly as I've been doing key binding stuff for a few hours today. :smile:

Use the key definition for P

---

examples/games/arkanoid/main.go

Adding arkanoid go port

---

raylib/textures.c

Link to original commit on main repo:
https://github.com/raysan5/raylib/commit/0eece03205b04f57f3a93a61c70eb1d69ac32977#diff-2b9ad86b4b0faabd6346b2799de91d35

Fixed issue with texture flip on X axis  (patch taken from main repo)

---

raylib/core.go

Added:
- IsWindowResized
- IsWindowHidden
- UnhideWindow
- HideWindow
- GetClipboardText
- SetClipboardText
- SetMouseOffset

Added Window, Clipboard and Mouse methods

---

raylib/core.c

Recent changes from upstream repo, correcting mouse position on mac.
[Original commit](https://github.com/raysan5/raylib/commit/f346c672fb411b33dc065188ef0d2f107ce55040)

Update C sources, macOS mouse position fix

---

raylib/core.go
raylib/text.go

I've made binds for some functions
**Text module:**
- LoadFontFromImage
- LoadFontData
- DrawTextRec
- DrawTextRecEx
- GetGlyphIndex
**Core module:**
- BeginScissorMode
- EndScissorMode
I don't know if some of this functions were not binded on purpose, in that case I'm sorry.
Anyway, I thought a little help might be great for you.

ScissorMode and Text functions

---

examples/core/2d_paint/main.go

Added paint example from the raylib C library

Added paint example

---

raymath/raymath.go

I recently tried to use "smooth lerping" in a demo with raylib but could't find it in the raylib-go implementation.
Thus I simple ported the source from the original raylib.h to the raymath package.

vector2 divide/multiply/lerp added

---

raylib/shapes.go

I added most of the remaining bindings of the shapes module.
I wasn't quite sure what to do with functions with a list as a parameter. In C is passed with the pointer and the number of elements,
```c
void DrawTriangleFan(Vector2 *points, int pointsCount, Color color)
```
but I chose the Go like solution of passing a slice of elements.
```go
func DrawTriangleFan(points []Vector2, color Color)
```
I'm open to any review or test.

Shapes bindings

---

examples/shaders/mesh_instancing/glsl330/base_lighting_instanced.vs
examples/shaders/mesh_instancing/glsl330/lighting.fs
examples/shaders/mesh_instancing/light.go
examples/shaders/mesh_instancing/main.go
raylib/models.go
raylib/raylib.go
raylib/raymath.go

* Expose DrawMesh/DrawMeshInstanced api.
* Ported example `shaders_mesh_instancing`.
* Add helper methods to Shader/Material in order to eliminate unsafe code in game's codebase.
* Bugfix: fix issue #138.

Add new api and example

---

raylib/rshapes.go

`DrawLineBezierQuad`
`DrawLineBezierCubic`
`DrawLineStrip`
`DrawPolyLinesEx`
Also moved `DrawRectangleV` up so it's in the same order as the cheatsheet

Added missing functions

---

raylib/raymath.go

Fixed #180 by assigning the result with the first quaternion argument.
I also refactored the normalization of the parameters.

fixed QuaternionNormalize

---

raylib/raymath.go

Add `MatrixRotateXYZ`

---

raylib/rcore.go

fixed GetTime return type.

---

raylib/raylib.go
raylib/utils.go
raylib/utils_android.go
raylib/utils_windows.go

Fix bitmasking for logging

---

raylib/rmodels.go

Adds two missing bindings for cylinder extra.

Adds DrawCylinderEx and DrawCylinderWiresEx bindings

---

raylib/rmodels.go

UploadMesh(mesh *Mesh, dynamic bool) added

---

raygui/raygui.go

Getter and setter for font added

---

raylib/raudio.go
raylib/raylib.go
raylib/rcore.go
raylib/rmodels.go
raylib/rtext.go
raylib/rtextures.go

#253 
@gen2brain  If there is still something missing, please tell me, otherwise I think we then can tag this as v4.5.0

Add more new functions (4.5.0 Update)

---

examples/shaders/raymarching/main.go
examples/shaders/raymarching/raymarching.fs

Hoping to help and wrote the Raymarching example from https://www.raylib.com/examples/shaders/loader.html?name=shaders_raymarching in Golang. It is working fine have tested and there is a need for many of the newer examples to be added.

Adding Raymarching Shaders Example

---

raylib/raylib.go

"KeyNull" added

---

examples/core/basic_window_manager/main.go
examples/core/smooth_pixelperfect/main.go
examples/shaders/multi_sample2d/color_mix.fs
examples/shaders/multi_sample2d/main.go

Have tested all working, no .exe files this time

Added more Core & Shader examples

---

raylib/raylib.go

Getters for Model type added

---

examples/shapes/easings_ball_anim/main.go
examples/shapes/easings_box_anim/main.go
examples/shapes/easings_rectangle_array/main.go

Sorry about last time, this time I have used easings as an import. Checked and working

Easings Examples Added

---

raylib/rmodels.go

This fixes the methods used to load and unload custom mesh data based on the content and info in #303

Bugfix for UploadMesh and UnloadMesh based on #303

---

raylib/raymath.go

Lift the Quaternion Eular methods from https://github.com/raysan5/raylib/blob/master/src/raymath.h#L2114

Add Quaternion Euler methods

---

raylib/raymath.go

The original method in raymath.h - https://github.com/raysan5/raylib/blob/master/src/raymath.h#L813

Add method to rotate vector by quaternion

---

examples/core/2d_camera_splitscreen/main.go
examples/core/3d_camera_splitscreen/main.go
examples/core/scissor_test/main.go

Add more core examples

---

README.md
raylib/go.mod
raylib/go.sum
raylib/purego_windows.go
raylib/raylib_purego.go

My goal is not to touch any existing code and have a kind of drop in replacement.
(related to the discussion #306)

First approach for purego

---

raylib/rtext.go

Change signature of LoadFontFromMemory in raylib/rtext.go

---

raylib/raylib_purego.go
raylib/rtextures.go

Simple PR to update the bindings to allow use of a rl function.

feat: update rtextures.go to have the func LoadTextureCubemap.

---

raylib/raylib_purego.go

This fixes https://github.com/gen2brain/raylib-go/issues/376

Don't use struct return values

---

raygui/raygui.go

[raygui] use nil for empty strings

---

raylib/raylib_purego.go

Vector4 has to be passed as pointer (not by value)

purego fix for ColorFromNormalized

---

raylib/raudio.go

Bindings for `AttachAudioMixedProcessor` and `DetachAudioMixedProcessor` calls.

bindings for attaching/detaching mixed audio processor

---

examples/core/3d_camera_first_person/main.go

3d camera first person example is updated to better match https://www.raylib.com/examples/core/loader.html?name=core_3d_camera_first_person

3d camera first person example updated

---

examples/core/2d_camera_platformer/main.go
examples/core/custom_frame_control/main.go
examples/core/custom_logging/main.go
examples/core/window_flags/main.go
examples/core/window_letterbox/main.go
examples/core/window_should_close/main.go

Here are 6 examples from https://www.raylib.com/examples (core section) that was missing:
2d camera platform
window should close
custom logging
custom frame control
window letterbox
window flags

6 new raylib/core examples

---

raylib/raylib_purego.go
raylib/rcore.go

vr functions added

---

examples/textures/draw_tiled/main.go

I changed the texture filter to TriLinear which I couldn't find before.

Small change in examples/texture/draw_tile

---

examples/core/storage_values/main.go

New example from [raylib.com](https://www.raylib.com/examples/core/loader.html?name=core_storage_values) : Core/storage_values

New example : Core/storage_values

---

raylib/raymath.go
raylib/raymath.h

Add function `MatrixDecompose`, allow to decompose matrix. Mostly use on matrix stacks with `Translatef`, `Rotatef`, and `Scalef`.

feat(raymath): `MatrixDecompose`

---

examples/core/vr_simulator/distortion100.fs
examples/core/vr_simulator/distortion330.fs
examples/core/vr_simulator/main.go
examples/shapes/draw_ring/main.go

Here is a new example from raylib.com Shapes section, Shapes/draw_ring.

New example: Shapes/Draw_ring

---

raylib/rtext.go

DrawTextCodepoint(s) functions added to cgo version

---

raylib/raudio.go

Is it right? Not sure how CGO wokrs
close #494

feat(raylib): adds UnloadSoundAlias function
