gen2brain/raylib-go

raylib/raylib.go

Started trying out raylib-go today, and noticed the fields in `VrDeviceInfo` aren't exported, which makes some things a bit weird to try and use.
For example, with the VR Simulator er... [example](https://github.com/gen2brain/raylib-go/blob/9b24dc61cfef0edecabcd62e45f1c28bb184e341/examples/core/vr_simulator/main.go#L8-L16), it's currently using hard coded values because it can't read them out of the structure.  If the fields are exported, then the VR example could be simplified ([something like this](https://github.com/justinclift/raylib-go/commit/83fae0be2e6a563eb4dbf028eb5ac1bd6c1ab501)) to just read the needed data directly.
Workable? :smile:

Export the VrDeviceInfo fields

---

examples/core/drop_files/main.go

There's a small bug in the drop_files example, whereby it does fine with single files being dropped but doesn't correctly calculate text position when multiple files are.  This PR addresses that.
It turns out this isn't a great example screenshot, as all of the file names are short so it's hard to see them writing over the top of each other. :roll_eyes:

Adjust drop_files example to cope with multiple dropped files

---

raylib/raylib.go

It was still referring to "raylib" instead of "rl".

Fix package name in documentation

---

raylib/raylib.go

Previously, the function broke on non-rectangular images.
Y needs to be multiplied by the horizontal width, not the image's reported height.

Fix: NewImageFromImage() height incorrect.

---

examples/utils/utils.go
raylib/utils_log.c
raylib/utils_log.go
raylib/utils_log.h

Hi, I've added a SetTraceLogCallback, including an example, with this we could get a callback and handle the trace log in go.
```go
rl.SetTraceLogCallback(func(logType int, str string) {
level := ""
switch logType {
case rl.LogDebug:
level = "Debug"
case rl.LogError:
level = "Error"
case rl.LogInfo:
level = "Info"
case rl.LogTrace:
level = "Trace"
case rl.LogWarning:
level = "Warning"
case rl.LogFatal:
level = "Fatal"
}
if logType != rl.LogFatal {
log.Printf("%s - %s", level, str)
} else {
log.Fatalf("%s - %s", level, str)
}
})
```
This allow to use your favourite go logger implementation such as https://github.com/sirupsen/logrus or others.
**Details:**
I've created 2 C Files that wrap the callback format a call a Go function, see: …

adding SetTraceLogCallback

---

raygui/raygui.go

Resolves an issue with ComboBox that led to the companion box showing item number/list size being oddly sized when using anything but a height of 20.
Does not alter behavior regarding scaling (specifying a large box does not increase the font size), since that seems contrary to intent.
Review Hint: For the changes to ComboBox, you may want to read the resulting ComboBox function directly: there's a large dedent and code reduction which make it hard to reason about in a diff view.
Before:
After:
Before:
After:

Cleanup of combobox and textheight

---

raylib/core.go

After updating the C source, GetKeyPressed returns the keycode instead of the char as always (read https://github.com/raysan5/raylib/commit/96542269d0ad8f7be9cfb4f0e9d02df2c45703ff for more).
This PR adds the `GetCharPressed` binding function which allows to retrieve the char instead of the keycode.

add GetCharPressed

---

raylib/textures.go

Added the following functions:
* ImageClearBackground
* ImageDrawPixel
* ImageDrawPixelV
* ImageDrawCircle
* ImageDrawCircleV
* ImageDrawRectangleV
* ImageDrawRectangleRec.
This is my first commit. I tried to alphabetically order the functions in the source code, as I believe that is what you guys have been doing.

Add 7 ImageDraw* functions

---

physics/physics.go

`fltMax` constant seems to have incorrect value `3.402823466 + 38` instead of `3.402823466e+38`.
But anyway, it makes more sense to use corresponding constant from math lib.

Physics: fix wrong max float

---

raylib/raymath.go

My last pull request #176 was technically correct, but I think we should be consistent with the raymath.h:
[https://github.com/raysan5/raylib/blob/master/src/raymath.h#L301](https://github.com/raysan5/raylib/blob/master/src/raymath.h#L301
)

Update Vector2Angle in raymath.go (again)

---

raylib/rcore.go

Fixed #201 by avoiding color.RGBA(), which scales component values to 0->65535 instead of the expected 0->255.

fixed ColorNormalize

---

raylib/rtextures.go

Hi there, I was playing around with the binding trying to generate an image without opening a window and I noticed these two functions were missing; so I went ahead and added them since the binding seems straightforward enough. Please point out if anything is not quite right :slightly_smiling_face:

Added ImageDrawLine and ImageDrawLineV functions to rtexture.go

---

raylib/rcore.go

GetFPS function now returns an int32 to mirror C version of raylib (https://github.com/raysan5/raylib/blob/master/src/rcore.c)

Fixed GetFPS return type

---

raylib/cgo_freebsd.go

Basically I just copied the `cgo_linux.go` to `cgo_freebsd.go` and added two new flags `-I/usr/local/include` and `-L/usr/local/lib` and had to remove `-Wno-stringop-overflow` (clang doesn't know this parameter).
FreeBSD stores header files and libraries in `/usr/local/*`. 
Also had to change `linux_joystick.c` to `null_joystick.c`. GLFW currently doesn't support gamepads: https://github.com/glfw/glfw/issues/1892
With that, I got it to run with clang (which is the default cgo compiler on FreeBSD) and gcc as well.

Adding FreeBSD support

---

raylib/cgo_openbsd.go

X11 libs and headers a located in `/usr/X11R6/lib` and `/usr/X11R6/include`
Also had to remove `-ldl` and `-lrt`: https://www.openbsd.org/faq/ports/guide.html
_OpenBSD does NOT require -lcrypt, -ldl, or -lrt. The functions provided by these libraries are part of libc. The crypt() function does not support DES, only bcrypt._ 
I successfully tested it on OpenBSD  7.2 with X11 and the default  window manager fvwm.

OpenBSD support added

---

raylib/utils.go

There was a typo in utils.go `rl.HomeDir()`.
The function returned a blank string if there was no error.

Typo in  rl.HomeDir()

---

raylib/raylib.go

The constants for the mouse cursor shapes were missed:
https://github.com/raysan5/raylib/blob/master/src/raylib.h#L670
For backwards compatibility I made MouseCursor a type alias, so it doesn't break `func SetMouseCursor(cursor int32)`

Mouse Cursor Enum added

---

raylib/rcore.go
raylib/rlgl.go
raylib/rshapes.go
raylib/rtextures.go

#255 
These are just some of the new functions

Add new functions (4.5.0 Update)

---

raylib/utils.go
raylib/utils_android.go

The C function in raylib is SetTraceLogLevel but in the go binding is SetTraceLog. I found this annoying so I have opened a pull request to fix it. If you want me to add other functions with the old name as well for backwards compatibility let me know. I just think that the Go API should match the C api. If you don't want to change this that's fine, then just close this PR.

rename SetTraceLog to SetTraceLogLevel

---

examples/shaders/custom_uniform/glsl330/swirl.fs
examples/shaders/custom_uniform/main.go
examples/shaders/postprocessing/glsl330/sobel.fs

In this PR my intent is to rename `texture2d()` to `texture()` to fix shader compilation errors on mac. `texture2d()` is deprecated and only compiles if compatibility profiles are implemented.

Fix texture2d as it is deprecated name

---

raygui/raygui.go

Hey!
When I tried to change the default text color to white using this:
```go
rg.SetStyle(rg.DEFAULT, rg.TEXT_COLOR_NORMAL, 0xffffffff)
```
I ran into an NumericOverflow error. This happens because the integer represented by `0xffffffff` is above the maximum value for `int32` ("lower" colors like `0x707070ff` are fine).
I am guessing this is an oversight? If so, changing the golang intermediaries to use int64 for the value fixes this problem, allowing the text to be set to white.

bugfix: change raygui.SetStyle and raygui.GetStyle to use int64 for the value

---

raygui/raygui.go

The TextBox widget on raygui was adding 0's to the end of the string indefinitely, so the string always grows in size. Fixed by removing the comments on the if statement that reduces allocation.
Also, included a Trim call to remove the 0's at the end of the string as it triggers erros when using this string with some go stdlib functinos.
Included the Trim calls missing on other text input widgets as well.

Fixing TextBox issue and adding Trim to other inputs

---

examples/games/life/main.go

rand.Seed is deprecated as of Go 1.20, update accordingly to Go's documentation.

fix: rand.Seed is deprecated

---

examples/games/snake/main.go

The snake example does not follow the original [raylib example](https://github.com/raysan5/raylib-games/blob/5ceec7c117a7f96504d215c6e49335848c4f7b2a/classics/src/snake.c#L208C108-L208C108)
The original example uses floating coordinates for the snake and fruit positions (I'm not sure if this is intentional), while the current raylib-go example uses integer coordinates for fruit spawning. This causes the collision calculation to be inaccurate, resulting in a bug where the snake can eat the fruit even when it is to the left of it.

Fixing snake example fruit spawning

---

raylib/rtextures.go

From the raylib docs, the returned Color list from LoadImageColors should be released with UnloadImageColors. Since the Go wrapper keeps the pointer to this data around (and wraps it into a Go slice), there needs to be a way to release the memory since the Go garbage collector will not properly dispose of the colors list and thus leak it. 
I noticed this issue when calling LoadImageColors in the gameloop causing memory to balloon. 
This could potentially be handled in the LoadImageColors function automatically with `runtime.SetFinalizer`. Thoughts?

Add UnloadImageColors

---

raylib/raylib.go

This PR adds the flag for borderless windowed mode.
Currently you can set this flag using: `rl.SetWindowState(0x00008000)`
Just adding it to constants.

Add flag for borderless windowed mode

---

raylib/rmodels.go

Surfacing the binding to the `DrawTriangle3D` method in `rmodels.go`.

Add binding for DrawTriangle3D to rmodels.go

---

physics/README.md

updated the link to point to what i assume is the new location of physac.h
from:
https://github.com/raysan5/raylib/blob/master/src/physac.h
to:
https://github.com/raysan5/physac/blob/master/src/physac.h

Updated link to physac.h

---

raygui/raygui.go

`mouseCell` in the Grid function never gets updated to the cell the mouse cursor is currently on.
I'm still new to Go so I hope this is the correct solution, as it seems to work correctly for me after this change

Fix Grid mouseCell not updaing value

---

physics/physics.go

physics.GetBodies: return only non nil (active) bodies

---

raylib/rlgl_cgo.go

This commit introduces functions related to compute shaders and Shader Buffer Storage Objects (SSBOs) in raylib-go. It adds bindings for loading, dispatching, and managing compute shaders and SSBOs, aligning raylib-go more closely with the raylib C library's capabilities. Specifically, the functions added are `LoadComputeShaderProgram`, `ComputeShaderDispatch`, `LoadShaderBuffer`, `UnloadShaderBuffer`, `UpdateShaderBuffer`, `BindShaderBuffer`, `ReadShaderBuffer`, and `CopyShaderBuffer`. These additions enhance raylib-go's utility for more advanced GPU operations.

Add Compute Shader and SSBO Functions to raylib-go

---

raylib/rlgl_cgo.go
raylib/rlgl_purego.go

This commit introduces functions related to compute shaders and Shader Buffer Storage Objects (SSBOs) in raylib-go. It adds bindings for loading, dispatching, and managing compute shaders and SSBOs, aligning raylib-go more closely with the raylib C library's capabilities. Specifically, the functions added are `LoadComputeShaderProgram`, `ComputeShaderDispatch`, `LoadShaderBuffer`, `UnloadShaderBuffer`, `UpdateShaderBuffer`, `BindShaderBuffer`, `ReadShaderBuffer`, and `CopyShaderBuffer`. These additions enhance raylib-go's utility for more advanced GPU operations.
Specifically in `rlgl_purego.go`

Add Compute Shader and SSBO Functions to raylib-go in `rlgl_purego.go`

---

raylib/raylib_purego.go
raylib/rtext.go

for many languages it is easier to load bunch of glyphs from font-file instead of declaring them upfront.

added LoadFontExByRunesNumber

---

raygui/raygui.go

The values on the view parameter of ScrollPanel() should be updated with the values set by the C method.
This can be verified in the scroll panel example. Before the fix, the grid was not rendered as the `panelView` rectangle is set to `rl.Rectangle{0, 0, 0, 0}` so scissor mode cut the entire grid. After the fix, the `panelView` rectangle is correctly sized and the grid is drawn with the appropriate clipping.

Fix ScrollPanel view binding

---

raylib/raylib_purego.go
raylib/rcore.go

Added `SwapScreenBuffer()` and `PollInputEvents` into rcore.go with corresponding comments.
To use them it's necessary to build with `CGO_CFLAGS="-DSUPPORT_CUSTOM_FRAME_CONTROL=1"`.
Also added more info in the raylib_purego.go file for theses two functions in order to inform that the dll must be recompiled

Added custom frame control functions to rcore.go

---

raylib/rcore.go

Defined for purego, but missing for cgo

Add missing WaitTime

---

raylib/rcore.go

Exposed existing `ToggleBorderlessWindowed()` function to golang side.
https://github.com/gen2brain/raylib-go/blob/f406ea403bc8762af8e9258a0feab83824e3467f/raylib/raylib.h#L968
https://github.com/gen2brain/raylib-go/blob/f406ea403bc8762af8e9258a0feab83824e3467f/raylib/platforms/rcore_desktop.c#L200
Tested it on my end using Windows but I have no experience working with bindings in golang. So not sure if there is more that needs to be done. If that's the case just let me know and I can add the work.

Expose ToggleBorderlessWindowed() to golang.

---

examples/audio/raw_stream/main.go

The current raw audio example has some problems:
- updates to the audio stream attempt to write a larger slice of data than the buffer size
- the method of choosing which parts of the data to add to the buffer does not account well for the current progress of the played sine wave
- there are some magic numbers that could use explanation, like the sine wave parameters and `maxSamples`.  changing `maxSamples` can also cause the audio not to play
This PR addresses these problems:
- the maxSamplesPerUpdate is set to 1600 by default now.  This many samples can be safely added to the audio buffer
- Timedelta from the start of the program is used to determine the part of the sine wave data to load into the buffer whenever the buffer needs to be reloaded.  This is the most important change.  It …

Improve raw audio example

---

raylib/purego_windows.go
raylib/raylib_purego.go
raylib/utils_log.c

- `TraceLog()` now uses fmt.Sprintf to match the cgo version
- The varargs are finally implemented for the TraceLogCallback function in purego. I used the wvsprintfA function for that. Microsoft advises to use other ones like for example StringCbVPrintfA, but they are not exported in any dll.

TraceLog and TraceLogCallback fixes

---

raylib/raymath.go
raylib/rcore.go
raylib/rlgl_purego.go

MultMatrix for purego added

---

examples/others/android/example/README.md
examples/others/android/example/androidcompile.bat

* Added `androidcompile.bat` as an example tool to help build on Windows
* Updated Readme.md with reference to Windows instructions
* Updated Readme.md with warning for incompatible NDK
* Updated Readme.md with reference to documentation for building android app bundles

Android example: Added windows.bat and updated Readme

---

raylib/raylib_purego.go

1. #172  was still present in purego-version
2. Without d374f90b4594c58f40c8e6a81d6ea8551236e0a8 the program will crash at runtime (structs > 64bit have to be passed as pointer)

Some fixes for purego-version

---

raylib/raylib.go
raylib/raylib_purego.go
raylib/rcore.go

Currently all the IsMouseButton* functions take in an int for the mouse button, which can be confusing for documentation reasons and has less type safety than if it used a newtype wrapper for int.
All I did is add a newtype & change the IsMouseButton functions accordingly.

[rcore] Added MouseButton newtype

---

raylib/raylib_purego.go
raylib/rtextures.go

Old version of NewImageFromImage converted colors incorrectly.
Which was discussed  in #412.
It used to look like this.
```Go
rcolor := NewColor(uint8(r), uint8(g), uint8(b), uint8(a))
```
Now it looks this.
```Go
rcolor := NewColor(uint8(r>>8), uint8(g>>8), uint8(b>>8), uint8(a>>8))
```
Just like in go [image package](https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/image/color/color.go;l=176).
Here's image demonstration.
Original jpeg image.
Before
After

Fix NewImageFromImage color converting

---

examples/core/3d_camera_free/main.go

Example `3d camera free` contained instructions that is no longer valid, I believe. They no longer exists on https://www.raylib.com/examples/core/loader.html?name=core_3d_camera_free, and I could not get them to work locally.

Removed erroneous instructions

---

examples/core/3d_camera_splitscreen/main.go

Synced example `3d camera splitscreen` with [raylib.com](https://www.raylib.com/examples/core/loader.html?name=core_3d_camera_split_screen).

Synced 3d camera splitscreen with raylib.com

---

examples/core/vr_simulator/distortion100.fs
examples/core/vr_simulator/distortion330.fs
examples/core/vr_simulator/main.go
examples/shapes/draw_circle_sector/main.go

New example for the shapes section : draw_circle_sector

New example: Shapes/draw_circle_sector

---

examples/text/input_box/main.go

Here is another example, [input_box](https://www.raylib.com/examples/text/loader.html?name=text_input_box), from the examples/text section of raylib.com that is missing on raylib-go.

New example: input_box

---

examples/text/rectangle_bounds/main.go

Here is another example, [rectangle_bounds](https://www.raylib.com/examples/text/loader.html?name=text_rectangle_bounds), from the examples/text section of raylib.com that is missing on raylib-go.

New example: rectangle_bounds

---

examples/models/animation/main.go

This example differed a little from raylib.com, added the missing red dots. [Animations](https://www.raylib.com/examples/models/loader.html?name=models_animation)

Fixed example that differed : models/animations

---

examples/models/billboard/main.go

This example differed a little from raylib.com, added the rotating [billboard](https://www.raylib.com/examples/models/loader.html?name=models_billboard).

Fixed example that differed : models/billboard

---

examples/models/mesh_generation/main.go

This [example at raylib.com](https://www.raylib.com/examples/models/loader.html?name=models_mesh_generation) has a custom mesh, which was missing in the golang example. So I added it...
However, the program panics when unloading the custom model. So I had to create the following function to clear the mesh before calling unload, and now it **does not panic**. 
I don't know if this is something that I don't understand, or if it is because of some underlying problem in the `Mesh` type, or `UnloadModel` function? Someone who knows more about the C code than me, might want to take a look at that.
```
func clearCustomMesh(models []rl.Model) {
// For some reason the custom model
// (id = 8) panics when unloading it.
// So we clear the mesh for it manually
// here.
models[8].Meshes.Vertices = nil …
```

Added a custom mesh to the example models/mesh_generation

---

examples/models/obj_loading/main.go

This example differed from the [raylib.com](https://www.raylib.com/examples/models/loader.html?name=models_loading) example, but it is now fixed.

Example fixed models/obj_loading

---

examples/models/animation/main.go
examples/models/gltf_loading/main.go
examples/models/m3d_loading/main.go
raylib/raylib.go

I added new receiver functions to the ModelAnimation type and updated the examples.
_ModelAnimation.FramePoses is a two dimensional array and you can now access it without using unsafe._

ModelAnimation improvements

---

raylib/raylib_purego.go

This solves my following comment:
https://github.com/gen2brain/raylib-go/issues/425#issuecomment-2422833027

fix purego version of DetachAudioStreamProcessor and DetachAudioMixedProcessor

---

examples/others/android/example/androidcompile.bat
raylib/platforms/rcore_android.c

Hello there!
Fix some issues related to Android compilation.

Android Compilation Enhancement

---

raylib/platforms/rcore_desktop_rgfw.c

When building with `-tags=rgfw` its said: `undefined reference to SetGamepadVibration`

rcore_desktop_rgfw.c SetGamepadVibration added

---

raylib/rlgl_cgo.go
raylib/rlgl_purego.go

Modified the `LoadTextureDepth` function in the Go bindings to return the texture depth ID (uint32). Previously, the function did not return anything, which made it difficult to access the texture ID directly in Go.

Add return value to `LoadTextureDepth`

---

raylib/platforms/rcore_drm.c

The was a problem building the lib on raspberry pi with '-tags drm'

Add GetClipboardImage for drm platform.

---

raylib/rlgl.go

missing constants from RLGL added 

---

raylib/raudio.go

The raylib functions `WaveFormat` and `WaveCrop` accept a pointer to `Wave` because the wave is updated in-place. However, the current Go bindings pass a copy of the wave to the C functions, so it is not updated. This commit changes the signatures of the Go API so they also accept a pointer to `Wave`.

Change `WaveFormat` and `WaveCrop` signatures to accept a pointer to `Wave`

---

raylib/raylib.go

I've begun implementing some of the things you mentioned on [the reddit post](https://www.reddit.com/r/raylib/comments/1l75oz8/comment/mwuyxhw/).
This PR just adds an alias `SetMain` for `rl.SetCallbackFunc `

Unite WASM bindings with the rest
